# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which your are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: amplified data
email: rcurrie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Software, Genomics and Machine Learning for the fun of it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ampdat.com" # the base hostname & protocol for your site
twitter_username: robertcurrie
github_username:  rcurrie

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
